Hodge-podge of new features
byuoitav/terraform-kubernetes-nginx-ingress-controller pull request #5
Opened 2020-07-29 07:23 UTC by garthwilliamson

Hi,

I've added a few new features we have found useful:

* Made the name configurable
* Added ability to set whitelisted IP addresses
* Added a pod disruption budget if there are multiple replicas
* Added priority class name

Let me know if you want individual pull requests for any of these or would prefer some changes. Also feel free to cherry pick as you please.

Cheers,
Garth

2020-08-05 16:32 UTC, dannyrandall requested changes
Thanks for adding this stuff! Here's a few changes that I think we should make before merging.

2020-08-05 16:32 UTC, dannyrandall commented on nginx.tf
> +    name      = "nginx"
```suggestion
    name      = var.name
```

2020-08-05 16:32 UTC, dannyrandall commented on nginx.tf
> +    max_unavailable = "50%"
```suggestion
    max_unavailable = var.disruption_budget_max_unavailable
```

2020-08-05 16:32 UTC, dannyrandall commented on variables.tf
> +  description = "The ip whitelist that is allowed to access the nlb"
```suggestion
  description = "The ip whitelist that is allowed to access the load balancer"
```

2020-08-05 16:54 UTC, garthwilliamson commented
Hi! I'm discovered a few other issues when I tried to use this to have two seperate ingresses rather than just one with a different name. I'll try to make a couple of pull requests here - I'll turn this one into everything _except_ the name change and create the name change as a new request, as I suspect there will be more conversation to have there around sensible defaults.

2020-08-06 08:14 UTC, garthwilliamson commented
I've changed this pull request to have only the following changes. When applying on top of master this adds a ["0.0.0.0/32"] to the load balancer config whitelisted ip addresses but makes no other changes (with the default configuration). If replicas is set more than 2, it adds the pod disruption budget as well.

* Added ability to set whitelisted IP addresses
* Added a pod disruption budget if there are multiple replicas
* Added priority class name

2020-08-06 15:52 UTC, dannyrandall approved these changes
lgtm. We'll merge this and figure out #7 before bumping the version.

2020-08-06 15:53 UTC, merged